---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, cloud manager, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention 
summary: NetApp SnapMirror는 LAN 또는 WAN을 통해 데이터를 고속으로 복제하여 가상 환경과 기존 환경 모두에서 높은 데이터 가용성과 빠른 데이터 복제를 실현할 수 있습니다. 데이터를 NetApp 스토리지 시스템에 복제하고 2차 데이터를 지속적으로 업데이트함으로써 데이터가 최신 상태로 유지되고 필요할 때마다 사용할 수 있고 외부 복제 서버가 필요하지 않습니다. 
---
= 복제 서비스에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror는 LAN 또는 WAN을 통해 데이터를 고속으로 복제하여 가상 환경과 기존 환경 모두에서 높은 데이터 가용성과 빠른 데이터 복제를 실현할 수 있습니다. 데이터를 NetApp 스토리지 시스템에 복제하고 2차 데이터를 지속적으로 업데이트함으로써 데이터가 최신 상태로 유지되고 필요할 때마다 사용할 수 있고 외부 복제 서버가 필요하지 않습니다.



== 피처

* ONTAP 스토리지 시스템 간에 데이터를 복제하여 클라우드 또는 클라우드 간 백업 및 재해 복구를 지원합니다.
* 고가용성으로 DR 환경의 안정성을 보장합니다.
* ONTAP 스토리지 간의 효율적인 블록 레벨 복제는 DR 및 백업을 위한 세분화된 복구 시점을 통해 빠르고 효율적입니다.




== 비용

NetApp은 복제 서비스 사용에 대한 비용을 청구하지 않지만, 클라우드 공급자에게 데이터 수신 및 송신 비용이 있는지 확인해야 합니다.



== 지원되는 작업 환경

Cloud Manager를 사용하면 다음 유형의 작업 환경 간에 데이터를 복제할 수 있습니다.

[cols="30,30"]
|===
| 소스 작업 환경 | 지원되는 대상 작업 환경 


| Cloud Volumes ONTAP  a| 
* ONTAP용 Amazon FSx
* Cloud Volumes ONTAP
* 온프레미스 ONTAP 클러스터




| 온프레미스 ONTAP 클러스터  a| 
* ONTAP용 Amazon FSx
* Cloud Volumes ONTAP
* 온프레미스 ONTAP 클러스터


|===


== 데이터 복제 작동 방식

Cloud Manager는 SnapMirror 및 SnapVault 기술을 사용하여 별도의 ONTAP 시스템에 있는 볼륨 간 데이터 복제를 단순화합니다. 소스 볼륨과 타겟 볼륨을 확인한 다음 복제 정책 및 일정을 선택하기만 하면 됩니다.

Cloud Volumes ONTAP의 경우 Cloud Manager가 필요한 디스크를 구매하고 관계를 구성하고 복제 정책을 적용한 다음 볼륨 간 기본 전송을 시작합니다.


NOTE: 기본 전송에는 소스 데이터의 전체 복사본이 포함됩니다. 후속 전송에는 소스 데이터의 차등 복제본이 포함됩니다.



== 지원되는 데이터 보호 구성

Cloud Manager는 단순, 팬아웃 및 계단식 데이터 보호 구성을 지원합니다.

* 간단한 구성에서는 볼륨 A에서 볼륨 B로 복제가 수행됩니다
* 팬아웃 구성에서는 볼륨 A에서 여러 대상으로 복제가 수행됩니다.
* 다중 구간 구성에서는 볼륨 A에서 볼륨 B로, 볼륨 B에서 볼륨 C로 복제가 수행됩니다

